package com.model;
// Generated Jun 24, 2018 4:41:05 PM by Hibernate Tools 4.3.1



/**
 * EncuestaRes generated by hbm2java
 */
public class EncuestaRes  implements java.io.Serializable {


     private Integer id;
     private String programa;
     private String genero;
     private int edad;
     private String bebida;

    public EncuestaRes() {
    }

    public EncuestaRes(String programa, String genero, int edad, String bebida) {
       this.programa = programa;
       this.genero = genero;
       this.edad = edad;
       this.bebida = bebida;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getPrograma() {
        return this.programa;
    }
    
    public void setPrograma(String programa) {
        this.programa = programa;
    }
    public String getGenero() {
        return this.genero;
    }
    
    public void setGenero(String genero) {
        this.genero = genero;
    }
    public int getEdad() {
        return this.edad;
    }
    
    public void setEdad(int edad) {
        this.edad = edad;
    }
    public String getBebida() {
        return this.bebida;
    }
    
    public void setBebida(String bebida) {
        this.bebida = bebida;
    }




}


